language: python

sudo: required

services:
- docker

python:
- '2.7'

install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt

script:
- (cd osm && python -m unittest discover)
- python -m unittest discover -s test/

before_install:
- docker build -t michaelvl/osmtracker --file docker/Dockerfile .

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push michaelvl/osmtracker;
  fi