language: python

python:
- '2.7'

install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt

script:
- (cd osm && python -m unittest discover)
- python -m unittest discover -s test/
