language: python

sudo: required

services:
- docker

env:
  global:
    - REPO=michaelvl/osmtracker
    - REPO_COMB=michaelvl/osmtracker-all-in-one
    - GITCOMMIT=${TRAVIS_COMMIT::7}

python:
- '2.7'

install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt

script:
- (cd osm && python -m unittest discover)
- python -m unittest discover -s test/
#- python -m unittest discover -s apiserver/test/


after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -t $REPO:git-$GITCOMMIT --file docker/Dockerfile .
- docker tag $REPO:git-$GITCOMMIT $REPO:$TAG
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker push $REPO:git-$GITCOMMIT
- docker push $REPO:$TAG

- docker build -t $REPO_COMB:git-$GITCOMMIT --file docker/Dockerfile-all-in-one .
- docker tag $REPO_COMB:git-$GITCOMMIT $REPO_COMB:$TAG
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker push $REPO_COMB:git-$GITCOMMIT
- docker push $REPO_COMB:$TAG
