language: python

sudo: required

services:
- docker

env:
  global:
    - REPO=michaelvl/osmtracker
    - GITCOMMIT=${TRAVIS_COMMIT::8}

python:
- '2.7'

install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt

script:
- (cd osm && python -m unittest discover)
- python -m unittest discover -s test/


after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -t $REPO:$COMMIT --file docker/Dockerfile .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker push $REPO
