version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    environment:
      DOCKER_REPO: michaelvl/osmtracker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variables
          command: |
            echo "DOCKER_REPO=$DOCKER_REPO" >> $BASH_ENV
            echo 'GITCOMMIT=${CIRCLE_SHA1::7}' >> $BASH_ENV
            GITCOMMIT=${CIRCLE_SHA1::7}
            NOW=$(date +%Y%m%d-%H%M)
            FULLNAME="$DOCKER_REPO:git-$NOW-$GITCOMMIT"
            echo "FULLNAME=$FULLNAME" >> $BASH_ENV
            echo "Branch $CIRCLE_BRANCH"
            echo "Using full name $FULLNAME"
      - run:
          name: Build container image
          command: |
            docker build -t $FULLNAME --file docker/Dockerfile .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $FULLNAME $DOCKER_REPO:latest
            fi
      # - run:
      #     name: Push container image
      #     command: |
      #       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #       docker push $DOCKER_REPO

  build_tester:
    docker:
      - image: circleci/python:3.7.1
    environment:
      DOCKER_REPO: michaelvl/osmtracker-tester
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variables
          command: |
            echo "DOCKER_REPO=$DOCKER_REPO" >> $BASH_ENV
            echo 'GITCOMMIT=${CIRCLE_SHA1::7}' >> $BASH_ENV
            GITCOMMIT=${CIRCLE_SHA1::7}
            NOW=$(date +%Y%m%d-%H%M)
            FULLNAME="$DOCKER_REPO:git-$NOW-$GITCOMMIT"
            echo "FULLNAME=$FULLNAME" >> $BASH_ENV
            echo "Branch $CIRCLE_BRANCH"
            echo "Using full name $FULLNAME"
      - run:
          name: Build container image
          command: |
            docker build -t $FULLNAME --file docker/Dockerfile-test-framework .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $FULLNAME $DOCKER_REPO:latest
            fi
      # - run:
      #     name: Push container image
      #     command: |
      #       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #       docker push $DOCKER_REPO

workflows:
  version: 2
  building:
    jobs:
      - build
      - build_tester
