version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    environment:
      DOCKER_REPO: michaelvl/osmtracker
      DOCKER_TESTER_REPO: michaelvl/osmtracker-tester
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variables
          command: |
            echo "DOCKER_REPO=$DOCKER_REPO" >> $BASH_ENV
            GITCOMMIT=${CIRCLE_SHA1::7}
            echo 'GITCOMMIT=$GITCOMMIT' >> $BASH_ENV
            FULLNAME="$DOCKER_REPO:git-$GITCOMMIT"
            echo "FULLNAME=$FULLNAME" >> $BASH_ENV
            FULLNAME_TESTER="$DOCKER_TESTER_REPO:git-$GITCOMMIT"
            echo "FULLNAME_TESTER=$FULLNAME_TESTER" >> $BASH_ENV
      - run:
          name: Build tester container image
          command: |
            docker build -t $FULLNAME_TESTER --file docker/Dockerfile-test-framework .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $FULLNAME_TESTER $DOCKER_TESTER_REPO:latest
            fi
      - run:
          name: Test osm tracker
          command: |
            docker run --rm -it -v ${PWD}:/osmtracker:ro $FULLNAME_TESTER /bin/bash -c "cd /osmtracker && ls"
            docker run --rm -it -v ${PWD}:/osmtracker:ro $FULLNAME_TESTER /bin/bash -c "cd /osmtracker && python -m unittest discover -s /osmtracker-test/test"
            docker run --rm -it -v ${PWD}:/osmtracker:ro $FULLNAME_TESTER /bin/bash -c "cd /osmtracker/osm && python -m unittest discover -s /osmtracker-test/osm-test"
            docker run --rm -it -v ${PWD}:/osmtracker:ro $FULLNAME_TESTER /bin/bash -c "cd /osmtracker && python -m pytest --tb=long /osmtracker-test/apiserver-test"
      - run:
          name: Build container image
          command: |
            docker build -t $FULLNAME --file docker/Dockerfile .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $FULLNAME $DOCKER_REPO:latest
            fi
      - run:
          name: Push container image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_REPO
