version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/python:3.7.1
    working_directory: ~/source
    environment:
      DOCKER_REPO: michaelvl/osmtracker
      DOCKER_TESTER_REPO: michaelvl/osmtracker-tester
      BASH_ENV: bash.env
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo "DOCKER_REPO=$DOCKER_REPO" >> $BASH_ENV
            GITCOMMIT=${CIRCLE_SHA1::7}
            echo 'GITCOMMIT=$GITCOMMIT' >> $BASH_ENV
            FULLNAME="$DOCKER_REPO:git-$GITCOMMIT"
            echo "FULLNAME=$FULLNAME" >> $BASH_ENV
            FULLNAME_TESTER="$DOCKER_TESTER_REPO:git-$GITCOMMIT"
            echo "FULLNAME_TESTER=$FULLNAME_TESTER" >> $BASH_ENV
      - save_cache:
          key: base-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/source
            - $BASH_ENV
  build:
    docker:
      - image: circleci/python:3.7.1
    working_directory: ~/source
    environment:
      BASH_ENV: bash.env
    steps:
      - run:
          name: Setup environment variables
          command: |
            echo "FULLNAME_TESTER is $FULLNAME_TESTER"
            echo "BASH_ENV is $BASH_ENV"
            cat $BASH_ENV
            source $BASH_ENV
            echo "2 FULLNAME_TESTER is $FULLNAME_TESTER"
      - restore_cache:
          key: base-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Build tester container image
          command: |
            docker build -t $FULLNAME_TESTER --file docker/Dockerfile-test-framework .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $FULLNAME_TESTER $DOCKER_TESTER_REPO:latest
            fi
      - run:
          name: Test osm tracker
          command: |
            # Mounting local paths as volumes are not possible with remote docker
            docker create -v /osmtracker --name osmsrc alpine:3.4 /bin/true
            docker cp . osmsrc:/osmtracker
            docker run --rm --volumes-from osmsrc $FULLNAME_TESTER /bin/bash -c "cd /osmtracker && python -m unittest discover -s /osmtracker-test/test"
            docker run --rm --volumes-from osmsrc $FULLNAME_TESTER /bin/bash -c "cd /osmtracker/osm && python -m unittest discover -s /osmtracker-test/osm/test"
            docker run --rm --volumes-from osmsrc $FULLNAME_TESTER /bin/bash -c "cd /osmtracker && python -m pytest --tb=long /osmtracker-test/apiserver/test"
      - run:
          name: Build container image
          command: |
            docker build -t $FULLNAME --file docker/Dockerfile .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $FULLNAME $DOCKER_REPO:latest
            fi
      - run:
          name: Push container image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_REPO

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
