dependencies:
- name: rabbitmq
  version: "0.6.13"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  alias: amqp

- name: mongodb
  version: "0.4.25"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  alias: db
