# Default values for osm-analytic-tracker.

# osm-analytic-tracker pods

difftracker:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  metrics:
    enabled: True

worker:
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

supervisor:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

frontend:
  replicas: 1
  service:
    name: osmtracker-frontend
    type: NodePort
    externalPort: 30000
    internalPort: 80

apiserver:
  enabled: false
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  service:
    name: osmtracker-apiserver
    type: NodePort
    externalPort: 30001

# shared between multiple osm-analytic-tracker pods

osmtracker:
  region: /osm-regions/denmark.poly
  map_scale: 6
  image:
    image: michaelvl/osmtracker
    tag: latest
    pullPolicy: IfNotPresent
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true

# supporting services

web:
  image:
    image: nginx
    tag: 1.11-alpine
    pullPolicy: IfNotPresent

db:
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 8Gi
  users:
    admin: adm.user
    admin_pass: adm.secret
    user_rw: rw.user
    user_rw_pass: rw.user.secret
    user_ro: ro.user
    user_ro_pass: ro.user.secret
  image:
    image: michaelvl/mongo
    tag: 3.4.1-1
    pullPolicy: IfNotPresent

