# Default values for osm-analytic-tracker.

# osm-analytic-tracker pods

difftracker:
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

filter:
  replicas: 2
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

analyser:
  replicas: 2
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

supervisor:
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

frontend:
  replicas: 1
  service:
    name: osmtracker-frontend
    type: NodePort
    externalPort: 30000
    internalPort: 80

apiserver:
  enabled: false
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  service:
    name: osmtracker-apiserver
    type: NodePort
    externalPort: 30001

# shared between multiple osm-analytic-tracker pods

osmtracker:
  debug: false
  region: /osm-regions/denmark.poly
  map_scale: 6
  image:
    image: michaelvl/osmtracker
    tag: latest
    pullPolicy: IfNotPresent
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
  networkpolicy:
    enabled: true
  metrics:
    enabled: true

amqp:
  enabled: true
  service:
    name: "amqp://user:rabbitpw@osmtracker-amqp"
  # RabbitMQ chart specific settings below
  #persistence: false
  rabbitmqUsername: user
  rabbitmqPassword: rabbitpw

# supporting services

web:
  image:
    image: nginx
    tag: 1.11-alpine
    pullPolicy: IfNotPresent

db:
  persistence:
    enabled: false
    volume:
      accessMode: ReadWriteOnce
      storageClass: null
      size: 8Gi
  users:
    admin: adm.user
    admin_pass: adm.secret
    user_rw: rw.user
    user_rw_pass: rw.user.secret
    user_ro: ro.user
    user_ro_pass: ro.user.secret
  image:
    image: michaelvl/mongo
    tag: 3.4.1-1
    pullPolicy: IfNotPresent

elasticsearch_gw:
  enabled: false
  elasticsearch_url: 'http://elastic:changeme@osmtracker-elasticsearch:9200'
  elasticsearch_index: 'osmtracker'
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
