# Default values for osm-analytic-tracker.

# osm-analytic-tracker pods

difftracker:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

worker:
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

frontend:
  replicas: 2
  service:
    name: osmtracker-frontend
    type: NodePort
    externalPort: 30000
    internalPort: 80

# shared between multiple osm-analytic-tracker pods

osmtracker:
  image:
    image: michaelvl/osmtracker
    tag: latest
    pullPolicy: IfNotPresent

# supporting services

web:
  image:
    image: nginx
    tag: 1.11-alpine
    pullPolicy: IfNotPresent

db:
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 8Gi
  dbadmin: adm.user
  dbadmin_pass: adm.secret
  dbuser_rw: rw.user
  dbuser_rw_pass: rw.user.secret
  dbuser_ro: ro.user
  dbuser_ro_pass: ro.user.secret
  image:
    image: michaelvl/mongo
    tag: 3.4.1-1
    pullPolicy: IfNotPresent

