# Default values for osm-analytic-tracker.

# osm-analytic-tracker pods

difftracker:
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

filter:
  replicas: 2
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

analyser:
  replicas: 2
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

supervisor:
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi

frontend:
  replicas: 1
  service:
    name: osmtracker-frontend
    type: NodePort
    externalPort: 30000
    internalPort: 80

# shared between multiple osm-analytic-tracker pods

osmtracker:
  debug: false
  region: /osm-regions/denmark.poly
  map_scale: 6
  image:
    image: michaelvl/osmtracker
    tag: latest
    pullPolicy: IfNotPresent
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
  networkpolicy:
    enabled: true
  metrics:
    enabled: true

# supporting services

amqp:
  service:
    name: "amqp://user:rabbitpw@osmtracker-amqp"
  # RabbitMQ chart specific settings below
  persistence:
    enabled: false
  rabbitmqUsername: user
  rabbitmqPassword: rabbitpw

web:
  image:
    image: nginx
    tag: 1.11-alpine
    pullPolicy: IfNotPresent

db:
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    storageClass: null
    size: 8Gi
  service:
    name: osmtracker-db
  mongodbUsername: rw.user
  mongodbPassword: rw.user.secret
  mongodbDatabase: osmtracker

# Optional components

apiserver:
  enabled: false
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  service:
    name: osmtracker-apiserver
    type: NodePort
    externalPort: 30001

elasticsearch_gw:
  enabled: false
  elasticsearch_url: 'http://elastic:changeme@osmtracker-elasticsearch:9200'
  elasticsearch_index: 'osmtracker'
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
