apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osmtracker-frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: osmtracker
        role: frontend
    spec:
      containers:
      - name: osmtracker-frontend
        image: michaelvl/osmtracker
        command: ["python", "/osmtracker/osm-analytic-tracker/osmtracker.py", "--db", "mongodb://osmtracker-database.default.svc.cluster.local", "--configdir", "/osmtracker-config"]
        args: ["run-backends", "--track"]
        imagePullPolicy: Always
        lifecycle:
          postStart:
           exec:
             command:
             - "cp"
             - "-rT"
             - "/html-init"
             - "/html"
        volumeMounts:
        - mountPath: /html
          name: html-volume
      - name: nginx
        image: nginx:1.11-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-volume
          readOnly: true
      volumes:
      - name: html-volume
        emptyDir:
          medium: "Memory"