apiVersion: v1
kind: Service
metadata:
  name: osmtracker-database
  namespace: osmtracker
  labels:
    app: osmtracker
    role: database
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: osmtracker
    role: database
