apiVersion: v1
kind: Service
metadata:
  name: osmtracker-frontend
  namespace: osmtracker
  labels:
    app: osmtracker
    role: frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: osmtracker
    role: frontend
