apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osmtracker-difftracker-deployment
  namespace: osmtracker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: osmtracker
        role: difftracker
    spec:
      containers:
      - name: osmtracker-difftracker
        image: michaelvl/osmtracker
        command: ["python", "/osmtracker/osm-analytic-tracker/osmtracker.py", "--db", "mongodb://osmtracker-database", "--configdir", "/osmtracker-config"]
        args: ["diff-fetch", "--track"]
        imagePullPolicy: Always
