apiVersion: v1
kind: Service
metadata:
  name: osmtracker-frontend
  namespace: osmtracker
  labels:
    app: osmtracker
    role: frontend-service
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.frontend.service.externalPort }}
  selector:
    app: osmtracker
    role: frontend
