apiVersion: v1
kind: Secret
metadata:
  name: osmtracker-secrets
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
type: Opaque
data:
  # Note: Read-only is separated from read/write although mongodb chart does not support this
  dbuser_ro: {{ .Values.db.mongodbUsername | b64enc | quote }}
  dbuser_ro_pass: {{ .Values.db.mongodbPassword | b64enc | quote }}
  dbuser_rw: {{ .Values.db.mongodbUsername | b64enc | quote }}
  dbuser_rw_pass: {{ .Values.db.mongodbPassword | b64enc | quote }}
