{{- if .Values.db.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | quote }}
{{- end }}
