apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osmtracker-difftracker-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.difftracker.replicas }}
  template:
    metadata:
      labels:
        app: osmtracker
        role: difftracker
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secret.yaml") . | sha256sum }}
    spec:
      strategy:
      - type: Recreate
      containers:
      - name: osmtracker-difftracker
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/osmtracker.py", "--db", "mongodb://$(DBUSER):$(DBPASSWD)@osmtracker-database/osmtracker", "--configdir", "/osmtracker-config"]
        args: ["diff-fetch", "--track"]
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw_pass
        resources:
{{ toYaml .Values.difftracker.resources | indent 10 }}
