{{- if .Values.db.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.server.persistentVolume.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.server.persistentVolume.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | quote }}
{{- end }}
