{{ if .Values.osmtracker.networkpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  policyTypes:
  - Ingress
  podSelector: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-db
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: osmtracker
      role: database
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: osmtracker
    ports:
    - protocol: TCP
      port: 27017
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-frontend
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: osmtracker
      role: frontend
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 80
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-metrics
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: osmtracker
      metrics: 'true'
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 8000
{{ end }}
