{{ if .Values.apiserver.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osmtracker-apiserver-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.apiserver.replicas }}
  template:
    metadata:
      labels:
        app: osmtracker
        role: apiserver
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: osmtracker-server
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/apiserver.py", "--db", "mongodb://$(DBUSER):$(DBPASSWD)@osmtracker-database/osmtracker", "--configdir", "/osmtracker-config"]
        args: []
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.osmtracker.securityContext | indent 10 }}
        env:
        - name: OSMTRACKER_REGION
          value: "{{ .Values.osmtracker.region }}"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro_pass
        resources:
{{ toYaml .Values.apiserver.resources | indent 10 }}
{{ end }}