apiVersion: v1
kind: Service
metadata:
  name: osmtracker-difftracker-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: osmtracker
    role: difftracker-metrics-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: osmtracker
    role: difftracker
