apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: osmtracker-difftracker-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.difftracker.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: osmtracker
        role: difftracker
        metrics: 'true'
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: osmtracker-difftracker
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/osmtracker.py"]
        args: [
               "--db", "mongodb://$(DBUSER):$(DBPASSWD)@osmtracker-database/osmtracker", "--configdir", "/osmtracker-config",
{{- if .Values.difftracker.metrics.enabled }}
               "--metrics",
{{- end }}
{{- if .Values.osmtracker.debug }}
               "-lDEBUG",
{{- end }}
               "diff-fetch", "--track"]
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.osmtracker.securityContext | indent 10 }}
        env:
        - name: OSMTRACKER_REGION
          value: "{{ .Values.osmtracker.region }}"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw_pass
        resources:
{{ toYaml .Values.difftracker.resources | indent 10 }}
