apiVersion: v1
kind: Secret
metadata:
  name: osmtracker-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  dbadmin: {{ .Values.db.users.admin | b64enc | quote }}
  dbadmin_pass: {{ .Values.db.users.admin_pass | b64enc | quote }}
  dbuser_rw: {{ .Values.db.users.user_rw | b64enc | quote }}
  dbuser_rw_pass: {{ .Values.db.users.user_rw_pass | b64enc | quote }}
  dbuser_ro: {{ .Values.db.users.user_ro | b64enc | quote }}
  dbuser_ro_pass: {{ .Values.db.users.user_ro_pass | b64enc | quote }}