{{ if .Values.osmtracker.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: osmtracker-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "osmtracker.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: metrics-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: {{ template "osmtracker.name" . }}
    metrics: 'true'
{{ end }}