apiVersion: apps/v1
kind: Deployment
metadata:
  name: osmtracker-filter-deployment
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
    component: filter
spec:
  replicas: {{ .Values.filter.replicas }}
  selector:
    matchLabels:
{{ include "osmtracker.labels.standard" . | indent 6}}
      component: filter
  template:
    metadata:
      labels:
{{ include "osmtracker.labels.standard" . | indent 8}}
        component: filter
        metrics: 'true'
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: osmtracker-filter
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/osmtracker.py"]
        args: [
{{- template "osmtracker.common_args" . }}
               "csets-filter"]
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.osmtracker.securityContext | indent 10 }}
        env:
        - name: OSMTRACKER_REGION
          value: "{{ .Values.osmtracker.region }}"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw_pass
        resources:
{{ toYaml .Values.filter.resources | indent 10 }}
