{{ if .Values.apiserver.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: osmtracker-apiserver-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "osmtracker.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.apiserver.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "osmtracker.name" . }}
        component: apiserver
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: osmtracker-server
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/apiserver.py"]
        args: [
{{- template "osmtracker.common_args" . }}
              ]
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.osmtracker.securityContext | indent 10 }}
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro_pass
        resources:
{{ toYaml .Values.apiserver.resources | indent 10 }}
{{ end }}