{{ if .Values.osmtracker.networkpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-db
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      release: {{ .Release.Name | quote }}
      # This comes from the subchart alias
      app: db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "osmtracker.name" . }}
    ports:
    - protocol: TCP
      port: 27017
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-frontend
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: {{ template "osmtracker.name" . }}
      component: frontend
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 80
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-amqp
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      release: {{ .Release.Name | quote }}
      # This comes from the subchart alias
      app: amqp
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 5672
{{ if .Values.osmtracker.metrics.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-metrics
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: {{ template "osmtracker.name" . }}
      metrics: 'true'
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 8000
{{ end }}
{{ end }}
