{{ if .Values.elasticsearch_gw.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osmtracker-elasticsearch-gw-deployment
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
    component: elasticsearch-gw
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "osmtracker.labels.standard" . | indent 6}}
      component: elasticsearch-gw
  template:
    metadata:
      labels:
{{ include "osmtracker.labels.standard" . | indent 8}}
        component: elasticsearch-gw
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: elasticsearch-gw
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/elastic-gw.py"]
        args: [
{{- template "osmtracker.common_args" . }}
	]
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.osmtracker.securityContext | indent 10 }}
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro_pass
        - name: ES_ENDPOINT
          value: {{ .Values.elasticsearch_gw.elasticsearch_url }}
        - name: ES_OSMTRACKER_INDEX
          value: {{ .Values.elasticsearch_gw.elasticsearch_index }}
        resources:
{{ toYaml .Values.elasticsearch_gw.resources | indent 10 }}
        volumeMounts:
{{ include "osmtracker.configmount" . | indent 8 }}
      volumes:
{{ include "osmtracker.configvolume" . | indent 6 }}
{{ end }}
