{{ if .Values.elasticsearch_gw.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: osmtracker-elasticsearch-gw-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: osmtracker
        role: elasticsearch-gw
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: elasticsearch-gw
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/elastic-gw.py", "-l", "DEBUG", "--db", "mongodb://$(DBUSER):$(DBPASSWD)@osmtracker-database/osmtracker"]
        #command: ["sleep", "100000"]
        args: []
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.osmtracker.securityContext | indent 10 }}
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro_pass
        - name: ES_ENDPOINT
          value: {{ .Values.elasticsearch_gw.elasticsearch_url }}
        - name: ES_OSMTRACKER_INDEX
          value: {{ .Values.elasticsearch_gw.elasticsearch_index }}
        resources:
{{ toYaml .Values.elasticsearch_gw.resources | indent 10 }}
{{ end }}
