{{- if .Values.db.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.db.persistence.volume.storageClass }}
  storageClassName: {{ .Values.db.persistence.volume.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.db.persistence.volume.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.volume.size | quote }}
{{- end }}
