apiVersion: apps/v1
kind: Deployment
metadata:
  name: osmtracker-supervisor-deployment
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
    component: supervisor
spec:
  replicas: {{ .Values.supervisor.replicas }}
  selector:
    matchLabels:
{{ include "osmtracker.labels.standard" . | indent 6}}
      component: supervisor
  template:
    metadata:
      labels:
{{ include "osmtracker.labels.standard" . | indent 8}}
        component: supervisor
        metrics: 'true'
      annotations:
        checksum/secrets: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-config.yaml") . | sha256sum }}
    spec:
      containers:
      - name: osmtracker-supervisor
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/osmtracker.py"]
        args: [
{{- template "osmtracker.common_args" . }}
               "supervisor", "--track"]
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.osmtracker.securityContext | indent 10 }}
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw_pass
        resources:
{{ toYaml .Values.supervisor.resources | indent 10 }}
        volumeMounts:
{{ include "osmtracker.configmount" . | indent 8 }}
      volumes:
{{ include "osmtracker.configvolume" . | indent 6 }}
