apiVersion: v1
kind: Service
metadata:
  name: osmtracker-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "osmtracker.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: frontend-service
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.externalPort }}
    targetPort: {{ .Values.frontend.service.internalPort }}
{{- if contains "NodePort" .Values.frontend.service.type }}
    nodePort: {{ .Values.frontend.service.externalPort }}
{{- end }}
    protocol: TCP
    name: {{ .Values.frontend.service.name }}
  selector:
    app: {{ template "osmtracker.name" . }}
    component: frontend
