{{ if .Values.apiserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: osmtracker-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "osmtracker.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: apiserver-service
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
  - port: {{ .Values.apiserver.service.externalPort }}
    targetPort: 5000
{{- if contains "NodePort" .Values.apiserver.service.type }}
    nodePort: {{ .Values.apiserver.service.externalPort }}
{{- end }}
    protocol: TCP
    name: {{ .Values.apiserver.service.name }}
  selector:
    app: {{ template "osmtracker.name" . }}
    component: apiserver
{{ end }}