apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osmtracker-database-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: osmtracker
        role: database
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.db.image.image }}:{{ .Values.db.image.tag }}"
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        env:
        - name: MONGODB_ADMIN
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbadmin
        - name: MONGODB_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbadmin_pass
        - name: MONGODB_DBNAME
          value: osmtracker
        - name: MONGODB_RW_USER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw
        - name: MONGODB_RW_PASS
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw_pass
        - name: MONGODB_RO_USER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro
        - name: MONGODB_RO_PASS
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_ro_pass
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
      - name: data
      {{- if .Values.db.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
