{{ if .Values.openstreetmap.externalApiService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openstreetmap.externalApiService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "osmtracker.labels.standard" . | indent 4}}
spec:
  type: ExternalName
  externalName: {{ .Values.openstreetmap.externalApiService.extname }}
{{ end }}