apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: osmtracker-analyser-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.analyser.replicas }}
  template:
    metadata:
      labels:
        app: osmtracker
        role: analyser
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/osmtracker-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: osmtracker-analyser
        image: "{{ .Values.osmtracker.image.image }}:{{ .Values.osmtracker.image.tag }}"
        command: ["python", "/osmtracker/osm-analytic-tracker/osmtracker.py"]
        args: [
{{- template "osmtracker.common_args" . }}
               "csets-analyse"]
        imagePullPolicy: {{ .Values.osmtracker.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.osmtracker.securityContext | indent 10 }}
        env:
        - name: OSMTRACKER_REGION
          value: "{{ .Values.osmtracker.region }}"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw
        - name: DBPASSWD
          valueFrom:
            secretKeyRef:
              name: osmtracker-secrets
              key: dbuser_rw_pass
        resources:
{{ toYaml .Values.analyser.resources | indent 10 }}
