apiVersion: v1
kind: Service
metadata:
  name: osmtracker-database
  namespace: {{ .Release.Namespace }}
  labels:
    app: osmtracker
    role: database
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: osmtracker
    role: database
